name: Bump versions based on labels

on:
    push:
        branches:
            - master
    pull_request:
        types:
            - labeled

jobs:
    labeler:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: bump version
              uses: haya14busa/action-bumpr@v1
              
