name: Tests
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: |
          flake8 . --count --max-line-length=127 --show-source --statistics

  test:
    name: CKAN 2.11
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:2.11-py3.10
      options: --user root
    services:
      solr:
        image: ckan/ckan-solr:2.11-solr9
      postgres:
        image: ckan/ckan-postgres-dev:2.11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - uses: actions/checkout@v6
    - name: Initialize git repository
      run: |
        git config --global user.email "test@example.com"
        git config --global user.name "Test User"
        git config --global --add safe.directory /__w/ckanext-unaids/ckanext-unaids
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: --cwd ckanext/unaids/react/ install
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: --cwd ckanext/unaids/react/ build
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install -e "git+https://github.com/fjelltopp/ckanext-scheming@fix/ckan-2.11-python-3.10-compatibility#egg=ckanext-scheming"
        pip install -e "git+https://github.com/fjelltopp/ckanext-validation@toavina/update-python#egg=ckanext-validation"
        pip install -e "git+https://github.com/fjelltopp/ckanext-ytp-request@toavina/update-python#egg=ckanext-ytp-request"
        pip install -e "git+https://github.com/datopian/ckanext-authz-service@d179b19469faff7e461191db53e31c60d19003bc#egg=ckanext-authz-service"
        # Python 3.10 compatibility patch for ckanext-authz-service
        sed -i 's/from collections import Iterable, defaultdict/from collections.abc import Iterable\nfrom collections import defaultdict/' /srv/app/src/ckanext-authz-service/ckanext/authz_service/authzzie.py
        pip install -e "git+https://github.com/ckan/ckanext-pages.git@6c8d5939b01964c30a0394f10fef6e8f5a210ada#egg=ckanext-pages"
        pip install -e "git+https://github.com/fjelltopp/ckanext-blob-storage@toavina/update-python#egg=ckanext-blob-storage"
        pip install -e "git+https://github.com/fjelltopp/ckanext-versions@toavina/update-python#egg=ckanext-versions"
        pip install -e "git+https://github.com/fjelltopp/ckanext-restricted@toavina/update-python#egg=ckanext-restricted"
        pip install -e .
        # Replace default path to CKAN core config file with the one on the container
        sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini
    - name: Setup ckan db
      run: ckan -c test.ini db init
    - name: Run tests
      run: pytest --ckan-ini=test.ini --cov=ckanext.unaids --disable-warnings ckanext/unaids/tests

  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
            node-version: 16.14.2
      - name: Setup extension
        run: |
          cd ./ckanext/unaids/react
          yarn
          yarn test --silent
